# TODO_AC Make an annotated version of this for future reference. I think these exist online.


# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS             += "meta-fet-distro"
BBFILE_PATTERN_meta-fet-distro  = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-fet-distro = "10"

LAYERDEPENDS_meta-fet-distro       = "core"
LAYERSERIES_COMPAT_meta-fet-distro = "scarthgap"
