# TODO_AC Make an annotated version of this for future reference. I think these exist online.


# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

# Does the name here have to match the layer (without "meta-")?
BBFILE_COLLECTIONS    += "fet"
BBFILE_PATTERN_fet     = "^${LAYERDIR}/"
BBFILE_PRIORITY_fet    = "10"

LAYERDEPENDS_fet       = "core"
LAYERSERIES_COMPAT_fet = "scarthgap"
