# Original file: layers/meta-karo-distro/conf/distro/karo-minimal.conf
# Pulls in layers/meta-karo-distro/conf/distro/include/karo-distro.inc
require conf/distro/include/karo-distro.inc

# TODO_AC: The script `karo-bsp/karo-setup-release.sh` checks for the prefix `karo-custom-<suffix>`,
# and automatically adds a later called `meta-<suffix>`. I don't think this name has more 
# significance beyond that. We could add a layer with any name manually, and use any name
# for the distro. It looks like the file name needs to match.
DISTRO = "karo-custom-neil"
DISTRO_NAME = "karo-custom-neil (Modified Ka-Ro Linux BSP with minimal read-only rootfs)"

# This lot was copied from the original file.
# TODO_AC Can we have a template of all the sorts of other things that go into a distro?

DISTRO_FEATURES:remove = " \
    gobject-introspection-data \
    multiarch \
    pulseaudio \
"

DISTRO_FEATURES_BACKFILL_CONSIDERED += " \
    gobject-introspection-data \
    pulseaudio \
"

# kernelfeatures not needed in minimal
DISTRO_FEATURES_DEFAULT:remove = " \
    csi-camera \
    imx219 \
    vivante_gpu \
"

MACHINE_EXTRA_RRECOMMENDS:remove = "imx-m4-demos"
MACHINE_EXTRA_RRECOMMENDS:remove = "udev-rules-imx"