# TODO_AL: This file was originally a clone of karo-minimal.conf.
# Can we just pull it in directly as a base?

require conf/distro/include/karo-distro.inc

# TODO_AL: The script `karo-bsp/karo-setup-release.sh` checks for the prefix `karo-custom-<suffix>`,
# and automatically adds a later called `meta-<suffix>`. I don't think this name has more 
# significance beyond that. We could add a layer with any name manually, and use any name
# for the distro. It looks like the file name needs to match.
DISTRO = "karo-custom-neil"
DISTRO_NAME = "karo-custom-neil (Modified Ka-Ro Linux BSP with minimal read-only rootfs)"

DISTRO_FEATURES:remove = " \
    gobject-introspection-data \
    multiarch \
    pulseaudio \
"

DISTRO_FEATURES_BACKFILL_CONSIDERED += " \
    gobject-introspection-data \
    pulseaudio \
"

# kernelfeatures not needed in minimal
DISTRO_FEATURES_DEFAULT:remove = " \
    csi-camera \
    imx219 \
    vivante_gpu \
"

MACHINE_EXTRA_RRECOMMENDS:remove = "imx-m4-demos"
MACHINE_EXTRA_RRECOMMENDS:remove = "udev-rules-imx"